[DEBUG]
render_one_file = true

[BOUNCE]
amplitude = 12
frequency = 20
decay = 8

[VIDEO]
width = 1920
height = 400
characters_per_second = 20

[TEXT]
text_size = 36
; NOT IMPLEMENTED YET, WON'T CHANGE ANYTHING
text_alignment = 0
text_x = 0
text_y = 0

[CHARACTER]
char_text_size = 48
; NOT IMPLEMENTED YET
; 0 to skip resizing
char_sprite_resize_x = 0
char_sprite_resize_y = 0

char_sprite_inverted = 0
char_sprite_alignment = 0
char_sprite_x = 0
char_sprite_y = 0
char_alignment = 0
char_text_x = 0
char_text_y = 0

[AUDIO]
minimum_pitch = 0.8
maximum_pitch = 1.2
pitch_modifier = 0.3
