[DEBUG]
; disables rendering of any files.
; true, false
no_render = false
; Put 0 to render all lines
amount_to_render = 0
; NOT IMPLEMENTED YET, WON'T CHANGE ANYTHING todo
; Put 0 to skip rendering specific lines
render_from = 0
render_to = 0

[BOUNCE]
amplitude = 3
frequency = 24
decay = 8

[VIDEO]
width = 1920
height = 400
characters_per_second = 25
fps = 20

[TEXT]
text_size = 36
; Left, Center, Right
text_alignment = Left
text_x = 10
text_y = 100
; true, false
text_padding_from_image = true

[CHARACTER]
char_text_size = 48
; Left, Center, Right
char_text_alignment = Center
char_text_x = 10
char_text_y = 60

; 0 on both(!) to skip resizing
char_sprite_resize_x = 0
char_sprite_resize_y = 0
char_sprite_inverted = 0
char_sprite_x = 0
; Y won't change if resizing is enabled.
char_sprite_y = 0
; NOT IMPLEMENTED YET. todo
char_sprite_alignment = 0

[AUDIO]
minimum_pitch = 0.8
maximum_pitch = 1.2
pitch_modifier = 0.5

[ADVANCED]
; NOT IMPLEMENTED YET. todo
; Time in seconds after next "breath". 
; Put 0 to disable breathing... guh damn.
breath_time = 0